# Generated by Django 4.2 on 2023-04-19 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='data_comment',
            new_name='date_comment',
        ),
    ]
